### ISSUE TITLE
Can't login, what am I missing?

### ISSUE THREAD

**Issue by leonnardo** [dcreemer/1pass#33]
I followed the instructions, created a `_master.gpg` and `_secret.gpg` files, but when I try:
```
> 1pass -rv
```

I got:
```
checking for op
checking for jq
checking for /usr/local/Cellar/gnupg/2.3.1_1/bin/gpg
checking for expect
signing in to my.1password.com <hiding email>
gpg: _master.gpg: skipped: No public key
gpg: [stdin]: encryption failed: No public key
```

And I have a gpg key created:
```
> gpg --list-public-keys
/Users/leonnardo.rabello/.gnupg/pubring.kbx
-------------------------------------------
pub   rsa2048 2021-06-18 [SC]
      D0040C15366FE9698F36D645032984594CD300AF
uid           [ultimate] Leonnardo Rabello <hiding email>
sub   rsa2048 2021-06-18 [E]
```

What am I missing?

**Comment by leonnardo** [comment]
Ok, I was messing up the parameter `self_key`.
I was using the filename `_master.gpg` instead of using the key id.. 

Sorry!

**Comment by dcreemer** [comment]
Sorry I missed this earlier but I'm glad you figured it out. If you feel the help text or instructions needs to more clear please send a PR!
