### ISSUE TITLE
1pass & iTerm2 integration.

### ISSUE THREAD

**Issue by birlorg** [dcreemer/1pass#34]
Hi!

So I wanted iterm integration like [sudolikeaboss](https://github.com/ravenac95/sudolikeaboss) did.  This was quite easy, but ran into a few little issues(which I worked around).

1) 1pass doesn't accept STDIN for the name of the item to fetch, which makes `fzf` and friends integration more annoying.

2) it doesn't search default paths, like `/usr/local/bin` or `/usr/bin`

This is how I worked around the issues:

create file /usr/local/bin/1piterm
```
#!/bin/sh
PATH=/usr/local/bin:/usr/bin
item=`/usr/local/bin/1pass | /usr/local/bin/choose`
/usr/local/bin/1pass -p $item
```

in iTerm2, go to preferences, then `keys`, add a new key open-apple+/ to `run coprocess` and run `/usr/local/bin/1piterm`

This uses the [choose](https://github.com/chipsenkbeil/choose) app instead of `fzf`, but you can replace choose with fzf without harm.

This then lets you get passwords into commands from iTerm2 by pressing the openapple+/ key searching for the name in the GUI that pops up and hitting enter.

Anyways, thanks for the awesome 1pass! made doing this very easy!

**Comment by dcreemer** [comment]
Hi -- thanks for this nice addition. I'm not sure I understand the PATH issue -- where does `1pass` not use the default $PATH correctly?

For the tip on how to integrate on iTerm2, I would love to add that to the documentation -- would you mind making a pull request with this information added to the README.md file?

Thanks!

**Comment by birlorg** [comment]
Sorry, I wasn't clear. You are 100% correct that `1pass` happily searches $PATH, it's just doesn't exist in Coprocess land.  In iTerm2 Coprocess land, it unsets $PATH.  This means of course that 1pass can't find anything it is looking for.  You have to set $PATH or hardcode the paths to the executables @ call time.

If you want to fix the STDIN issue, then we can get around needing a shell script wrapper, and then it can all be pure documentation on how to do it, which I'd be happy to write.  Otherwise you kind of need a wrapper, as it's hard to get more than 1 line in that coprocess iterm2 window config.  If you don't want to fix STDIN, then probably the best way is add a wrapper file AND add documentation.  Your call, just let me know.

**Comment by dcreemer** [comment]
OK thanks for clarifying -- I'll install iTerm2 and play a bit to better understand the issue. In the meantime I think that taking the item search key from stdin is quite reasonable. So the following would be equivalent:

```sh
$ 1pass -p foo
foopass
$ echo -n "foo" | 1pass -p -
foopass
```

here `-` indicates taking the key from stdin. If that meets your needs I can implement that.

**Comment by birlorg** [comment]
That would work fabulously.  that would make the fuzzpass.sh/.fish unneeded also, as then it would be as simple as:

`1pass | fzf | 1pass -p -`

**Comment by dcreemer** [comment]
I've pushed [release v1.5](https://mac.getutm.app/gallery/debian-10-4-minimal) to support specifying the search text from `stdin`.

**Comment by birlorg** [comment]
Also I think integration with KITTY is possible as well, doing something like this: https://github.com/kovidgoyal/kitty/issues/1222#issuecomment-447607674

I haven't gotten around to doing this yet.  This comment is mostly as a note to myself for future me, when I get that far, provided someone else doesn't beat me to it.  I'm not currently aware of any other way to do it on other platforms.
