### ISSUE TITLE
line 511: get_fields_003: command not found

### ISSUE THREAD

**Issue by busla** [dcreemer/1pass#36]
First, thanks for contributing this amazing tool!

And now the bug 😄 

I have a _secure note_ in 1pass and when querying the fields for the item I get the following error:
```bash
line 511: get_fields_003: command not found
```
Looking at the source code, I can see that the function does not exist.

Perhaps only _login_ items are supported?

**Comment by dcreemer** [comment]
Thanks for this note! I will look into addressing this as soon as I can.

If you want to play with a little Bash coding, I'm guessing this could be a copy/paste exercise to add, using some of the other record types as examples.

**Comment by busla** [comment]
Definitely!

I'll try to make a PR this week.

**Comment by busla** [comment]
Done https://github.com/dcreemer/1pass/pull/37/files

**Comment by dcreemer** [comment]
thanks! I'll review it tonight.

**Comment by dcreemer** [comment]
Brilliant. Merged -- thanks! https://github.com/dcreemer/1pass/releases/tag/v1.6
