### ISSUE TITLE
Support Wayland - *NIX systems not using X11 based `xclip`

### ISSUE THREAD

**Issue by maricn** [dcreemer/1pass#41]
Atm the `1pass` command fails to start due to `xclip` missing, even if comparable `wl-copy` command is more commonly used on Wayland (wl-roots) based systems that aren't running X11.

I will provide a PR to address this.

**Comment by dcreemer** [comment]
fixed in #42 .
Thanks @maricn !

**Comment by dcreemer** [comment]
fixed
