### ISSUE TITLE
xclip command when copying get_result

### ISSUE THREAD

**Issue by nicolasm** [dcreemer/1pass#9]
Hi,
It should be xclip -selection clipboard selection instead of xclip -i.

With xclip -i nothing gets copied to the clipboard if you are using Linux.

By the way, great wrapper!
Nicolas

**Comment by dcreemer** [comment]
hi - thanks for the feedback -- can you submit a PR? I don't currently have a Linux desktop to test this.

**Comment by nicolasm** [comment]
Done.

**Comment by dcreemer** [comment]
merged PR https://github.com/dcreemer/1pass/pull/12
